### ISSUE TITLE
snpEff download directory only works with a trailing slash

### ISSUE THREAD

**Issue by bensprung** [moiexpositoalonsolab/grenepipe#12]
It appears that the snpeff `download-dir` parameter in `config.yaml `must have a trailing slash to work properly, e.g. "`/home/ben/my_download_dir/`" works but with "`/home/ben/my_download_dir`" the downloads just go to my home folder. Not sure if that is the intended behavior (maybe just a warning about this in the comments would suffice?).

**Comment by lczech** [comment]
Weird. Okay, will investigate once I get to work on #13 ;-)

**Comment by bensprung** [comment]
Sounds good! I'll try to investigate as well.

**Comment by lczech** [comment]
Fixed, finally ;-)
