### ISSUE TITLE
feature request: pass local reference genome database to snpEff

### ISSUE THREAD

**Issue by bensprung** [moiexpositoalonsolab/grenepipe#13]
The pre-built references databases that snpEff can download may be limiting in some use cases. Therefore it might be helpful to allow the use of user-prepared reference databases.

**Comment by lczech** [comment]
Hi @bensprung,

yes, this is already on my todo list. Let's see when I get to do this ;-)

Lucas

**Comment by lczech** [comment]
Finally added in the latest commit. Hope that helps, @bensprung ;-)
