### ISSUE TITLE
support for haploid genomes?

### ISSUE THREAD

**Issue by bensprung** [moiexpositoalonsolab/grenepipe#15]
The documentation for GATK's haplotypecaller says "This tool is able to handle many non-diploid use cases; the desired ploidy can be specified using the -ploidy argument". I am working with haploid yeast. So I would like to be able to pass the argument `-ploidy 1` to haplotypecaller, is there a way to do this? Thanks!

**Comment by bensprung** [comment]
So it seems to work find with "`-ploidy 1`" passed along. No more pesky `0|1`'s!

**Comment by lczech** [comment]
Awesome! And none of the downstream tools complained about this? I'm closing this issue then - but feel free to re-open if needed :-)

Also, thanks for hint about swapped links!

**Comment by bensprung** [comment]
Apparently not, at least the snpeff output looks like it makes sense so far.

**Comment by lczech** [comment]
Perfect, glad to hear :-)
