### ISSUE TITLE
Change link in wiki 

### ISSUE THREAD

**Issue by Tatianabellagio** [moiexpositoalonsolab/grenepipe#19]
In the wiki:
'Samples can either be in fastq format, or in compressed fastq.gz format (the file extension itself does not matter though). See also our exemplary table.' 
the link should be changed
https://github.com/moiexpositoalonsolab/grenepipe/blob/master/data/samples.tsv
https://github.com/moiexpositoalonsolab/grenepipe/blob/master/example/samples.tsv

XOXOXOXOXO

**Comment by lczech** [comment]
Thank you, fixed it ;-)
