### ISSUE TITLE
GATK Realigner

### ISSUE THREAD

**Issue by florianhahn87** [moiexpositoalonsolab/grenepipe#2]
Hey again :)

Is it possible to add the RealignerTargetCreator and the IndelRealigner from GATK to the pipeline as this always improves our alignments a lot or am I missing an option in the config.yaml file where I can do that already? 

Thanks a lot,
Florian

**Comment by lczech** [comment]
Hey Florian,

it seems that GATK4 HaplotypeCaller (which we use here) already does these steps, making the GATK3 tools you mentioned obsolete. See [the end of this post](https://gatk.broadinstitute.org/hc/en-us/articles/360038154292-Welcome-to-the-new-home-of-GATK):

> Yes we dropped the indel realignment step from the Best Practices; I think that was about 2 years ago. There was a blog post about it. We found that this step was no longer useful when the variant calling was done with HaplotypeCaller or Mutect2, which implement a more sophisticated and effective form of realignment.

I couldn't find this blog post, but still, it seems, support for these tools has been dropped. So, I guess you should be good without them - what do you think? Furthermore, the RealignerTargetCreator seems to create an "intervals" file as its output, and I am not sure how this would help or be incorporated into the downstream steps.

Cheers
Lucas

**Comment by florianhahn87** [comment]
Oh, perfect, thanks for the clarification, we missed that change from GATK3 to 4! Thanks!
