### ISSUE TITLE
BaseRecalibrator error - needs more readgroup info?

### ISSUE THREAD

**Issue by mvdloosdrecht** [moiexpositoalonsolab/grenepipe#20]
Hi Lucas,

I would like to ask for your help with an error that occurs when trying to run the rule recalibrate_base_qualities (details are below). I suspect that this error happens because the current default settings in the snakemake file for bwa mem -R result in BAM headers that contain info for the fields ID and SM, but not for platform unit (PU) and platform type (PL).  

If I understood the GATK BaseRecalibrator documentation well, the BaseRecalibrator may not work without the PU field. This PU field ({FLOWCELL_BARCODE}.{LANE}.{SAMPLE_BARCODE} holds the information for which library a read belongs to and what lane it was sequenced in on the flowcell. (https://gatk.broadinstitute.org/hc/en-us/articles/360035890671-Read-groups, https://gatk.broadinstitute.org/hc/en-us/articles/360035890531-Base-Quality-Score-Recalibration-BQSR-, https://gatk.broadinstitute.org/hc/en-us/articles/360036898312-BaseRecalibrator) 
 
Do you think that this could indeed be the reason for the error message? If yes, do you know how I can extend the bwa mem -R command so that the RG tag includes the PU and PL info? 

Thanks!

Marieke

 
## The error message I get in the .log file of the snakemake run: 
 ```
RuleException: 
CalledProcessError in line 142 of /[..]/grenepipe-0.6.0/rules/mapping.smk: 
Command 'source /[..]/mambaforge/bin/activate '/[..]/bin/mambaforge/envs/grenepipe/stable_conda_bin/6ab4ef66d24710ce1dcec6e2ab21e95e'; set -euo pipefail;  python /[..]/.snakemake/scripts/tmppyqdpcnq.wrapper.py' returned non-zero exit status 1. 
  File "/[..]/grenepipe-0.6.0/rules/mapping.smk", line 142, in __rule_recalibrate_base_qualities 
  File "/[..]/mambaforge/envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run 
```

## The error message in '/logs/gatk/bqsr/DRR058051-1.log': 
 ```
A USER ERROR has occurred: Read DRR058051.2067319 1:1000-1050 is malformed: The input .bam file contains reads with no platform information. First observed at read with name = DRR058051.2067319 
```

## The default settings for the rule recalibrate_base_qualities in the 'mapping-bwa-mem.smk' file: 
 ```
rule map_reads: 
    input: 
        reads=get_trimmed_reads, 
        ref=config["data"]["reference"]["genome"], 
        refidcs=expand( 
            config["data"]["reference"]["genome"] + ".{ext}", 
            ext=[ "amb", "ann", "bwt", "pac", "sa", "fai" ] 
        ) 
    output: 
        "mapped/{sample}-{unit}.sorted.bam" 
    params: 
        index=config["data"]["reference"]["genome"], 
 
        # We need the read group tags, including `ID` and `SM`, as downstream tools use these. 
        extra=r"-R '@RG\tID:{sample}\tSM:{sample}' " + config["params"]["bwamem"]["extra"], 
        # TODO Add LD field as well for the unit?! http://www.htslib.org/workflow/ 
        # If so, same for bwa aln and bwa mem2 rules as well? 
```

**Comment by lczech** [comment]
Hi @mvdloosdrecht,

very sorry for my late reply. I'm on it, but it will take a bit to get this to work with all mappers and callers...

So long
Lucas

**Comment by lczech** [comment]
Hey @mvdloosdrecht,

thanks for your patience! I just pushed an update in the above commit that should fix this, for all mapping tools. Let me know if that works for you.

Closing the issue now, but feel free to re-open should there still be any problems with this.

Cheers and so long
Lucas
