### ISSUE TITLE
CondaMemoryError when creating conda envs in cluster

### ISSUE THREAD

**Issue by orangelc1221** [moiexpositoalonsolab/grenepipe#22]
Hello,
I would like to run the pipeline on the cluster of my university. I Installed the conda enviroment(grenepipe) with the yaml file. I am trying this step:
snakemake \
    --conda-frontend mamba \
    --conda-prefix ~/conda-envs \
    --profile profiles/slurm/ \
    --directory /path/to/data

However our cluster doesn't have mamba installed, so I skip the --conda-frontend. Snakemake started to work, but I keep receiving the error

CreateCondaEnvironmentException:
Could not create conda environment from xxx/grenepipe-master/rules/../envs/picard.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

CondaMemoryError: The conda process ran out of memory. Increase system memory and/or try again.

I tried many times, and I modified the cluster_config.yml file under /profiles/slurm. I changed the _default_ mem to up to xxxG, but it still failed quite fast (after several mins). And suggestions? 

Our cluster does have guidelines on running snakemake on the cluster, with a script run.slurm. But I am a bit confused about how it should work with all the setting files grenepipe provided. Should I actually put the above snakemake commands into this run.slurm file and run it accordingly? In my previous trials, I just run this snakemake command on terminal.

Thank you!

Best,
lc

**Comment by orangelc1221** [comment]
Thank you!

**Comment by lczech** [comment]
You're welcome! For future reference: Did this solve all issues you had, and is it working now?
