### ISSUE TITLE
Make "trimming-tool" optional

### ISSUE THREAD

**Issue by coolkom** [moiexpositoalonsolab/grenepipe#35]
Hello,
I had a first look to grenepipe and first, thanks for a handy tool.
Would it be possible to make the "trimming-tool" step optional please ? Currently, valid values are: "adapterremoval", "cutadapt", "fastp", "seqprep", "skewer", "trimmomatic". But there are cases where you already have manually demultiplexed, removed adapters and trimmed the reads. So, the prepared fastq files could directly be used for mapping.
Thanks.

Cheers,
Coolkom.

**Comment by lczech** [comment]
Hi @coolkom,

thanks for the suggestion, that's a good idea. I'm a bit swamped with other things at the moment, and will likely not get to implement that in the next couple of weeks. 

In the meantime, would it work for you to still run it with a trimming tool? I'm not sure how these tools exactly behave if there is nothing to trim, but chances are that they just don't do anything, and just output the input again. So then you would be able to use the rest of the pipeline then. But please check that ;-)

Cheers
Lucas

**Comment by coolkom** [comment]
Thanks Lucas.
Yes I think that should be the behaviour if there is no adapters to remove or trimming to do. Just a waste of time and ressources dedicated to a useless step.
I will check.

Cheers,
Coolkom.

**Comment by lczech** [comment]
Okay, that makes sense. Let's keep the issue open for now, and I'll see when I get to implement this. But as long as it still works generally for you, that's good :-)

**Comment by lczech** [comment]
Hey @coolkom,

finally implemented this in [grenepipe v0.13.0](https://github.com/moiexpositoalonsolab/grenepipe/releases/tag/v0.13.0). Thanks again for the suggestion!

Cheers
Lucas
