### ISSUE TITLE
more problems with version  0.13.1

### ISSUE THREAD

**Issue by ospfsg** [moiexpositoalonsolab/grenepipe#58]
Dear Lucas

Finally I try to run grenepipe after installing the environment with micromamba.

I update the config file and add the relevant information as I did with previous version that I run in version 0.12.
 
But this time  
[2024-10-21T111227.306719.snakemake.log](https://github.com/user-attachments/files/17472428/2024-10-21T111227.306719.snakemake.log)
it stops  in early stage....I attached the log file.

I have this messages: 

 
![image](https://github.com/user-attachments/assets/1bc29b96-0f6a-4696-8354-703be93da7cf)

![image](https://github.com/user-attachments/assets/c18bae88-395a-43fe-a883-342aff1b3a86)

![image](https://github.com/user-attachments/assets/8b12b7ec-29d4-4905-b05f-e69f4c6f7d40)

any suggestion?

thank you
osp

**Comment by lczech** [comment]
Hi Octavio,

hm, I think I have seen this one before, but can't quite remember. The log file you appended is the regular one from Snakemake, right? Unfortunately, the Snakemake version we are currently using does not print my custom grenepipe header to the log file, which however contains important information for me to debug this. Could you please also attach the log file for this run that is stored in the working directory of your run, under `logs/snakemake`?

My best guess with the information that I have right now is that somehow, the base conda environment from which you run grenepipe has a conflicting numpy version. Are you calling grenepipe with the conda environment active that you used for a previous version of grenepipe? That likely will not work. You will have to follow the [Preparing the environment](https://github.com/moiexpositoalonsolab/grenepipe/wiki/Setup-and-Usage#preparing-the-environment) steps again, and create a new environment which contains the updated versions of everything. For this, you can either delete the previous `grenepipe` conda environment, or, what I like to do, is create a new one with a new name. 

For instance, the way that I set this up is using the following command to create the env:

    micromamba env create -f workflow/envs/grenepipe.yaml -n grenepipe-v0.13.1

The difference to the documented command is the suffix with the grenepipe version for the name (option `-n`) of the environment. Before running this command, make sure to deactivate any other environments that you might be in (`micromamba deactivate`). After that, you need to activate that particular environment of course (using the name that you gave it above).

Let me know if that solves the issue.

Cheers
Lucas

**Comment by ospfsg** [comment]
First I attached the log file you ask.
[2024-10-21T111226.651528.log](https://github.com/user-attachments/files/17474465/2024-10-21T111226.651528.log)

Second: I removed the previous grenepipe  env

conda env remove -n grenepipe

then I instaled  micromamba

"${SHELL}" <(curl -L micro.mamba.pm/install.sh) 

micromamba self-update

Your micromamba version (2.0.2) is already up to date.

then create and activate a conda environment for running snakemake.
cd /path/to/grenepipe

micromamba env create -f workflow/envs/grenepipe.yaml

micromamba activate grenepipe

and then I run the command: 
(grenepipe) dau1@frey:~/software/grenepipe-0.13.1$ snakemake  --use-conda --conda-frontend mamba --cores  102  --directory  /mnt/data3/Project_KeePace/Operational/4_data_analysis/5_grenepipe/run5/  --conda-prefix /home/dau1/software/conda-envs/


my installation env create is different since I didn´t add the -n grenepipe-v0.13.1.

but: 
1 -I removed the previous conda env grenepipe, in miniconda3/envs there is no trace of grenepipe
2- I installed micromamba for the first time. The grenepipe env is there, and is so far the only env there

![image](https://github.com/user-attachments/assets/102e1f69-1baa-443f-a333-af6876a7e257)

do you still think that is the -n stuff?  I can remove and create again  the environment.

osp

**Comment by jfaberha** [comment]
Has this been solved? I'm encountering the same Numpy error and tried resetting the grenepipe environment as recommended. Log file attached from my latest test run of run.sh
[test-run.log](https://github.com/user-attachments/files/17927453/test-run.log)

**Comment by lczech** [comment]
Hi @ospfsg and @jfaberha,

thanks for your patience here - it is tricky to keep maintaining grenepipe when the whole Snakemake/conda/mamba ecosystem keeps breaking backwards compatibility. I'm trying to catch up, but always one step behind the latest issue on their end...

Anyway, I have attempted a fix on the `master` branch. Could you please download that via the green "Code" button [on the main repository page](https://github.com/moiexpositoalonsolab/grenepipe), and see if that works? 

Cheers
Lucas

**Comment by jfaberha** [comment]
Hi Lucas,
This seems to fix the issue. Thank you so much. Looking forward to playing
around with the pipeline a bit more now. I'll let you know if I run into
any other issues further down the line.
-Josh

**Comment by lczech** [comment]
Hi @jfaberha,

thanks for the confirmation! I just released [grenepipe v0.13.2](https://github.com/moiexpositoalonsolab/grenepipe/releases/tag/v0.13.2), which contains the fix.

Closing the issue now. @ospfsg, I think that this should solve your errors as well. If not, as always, just open a new issue ;-)

Cheers and so long
Lucas
